############# Saes Development ##########
## This Config File is Minimal, Please ##
## Put in just the message, and you're ##
## Ready to use the plugin.            ##

############ Support? ###################
## IRC: #Saes on irc.esper.net         ##
#########################################

message: I told you I would get My Revenge